---
- job:
    name: masakari-functional-devstack-multinode
    parent: devstack
    description: |
      Masakari functional tests job based on devstack (two-node).
    nodeset: openstack-two-node-focal
    pre-run: playbooks/devstack/pre.yaml
    run: playbooks/devstack/run.yaml
    post-run: playbooks/devstack/post.yaml
    required-projects:
      - openstack/masakari
      - openstack/masakari-monitors
    irrelevant-files:
      - ^api-ref/
      - ^doc/
      - ^masakari/tests/unit/
      - ^releasenotes/
      - ^\.coveragerc$
      - ^\.gitignore$
      - ^\.gitreview$
      - ^\.mailmap$
      - ^\.yamllint$
      - ^\.zuul\.yaml$
      - ^LICENSE$
      - ^.*[^/]+\.rst$
      - ^bindep\.txt$
    vars:
      devstack_plugins:
        masakari: https://opendev.org/openstack/masakari
      devstack_services:
        # FIXME(yoctozepto): Make the job tls-proxy-compatible.
        tls-proxy: false
        # NOTE(yoctozepto): Disable controller's cinder (c-* services).
        # It is enabled by default by the parent job (devstack) definition.
        cinder: false
        # NOTE(yoctozepto): Disable controller's swift (s-* services).
        # It is enabled by default by the parent job (devstack) definition.
        swift: false
    host-vars:
      controller:
        tox_install_siblings: false
        tox_envlist: functional
    group-vars:
      subnode:
        devstack_services:
          # FIXME(yoctozepto): Make the job tls-proxy-compatible.
          tls-proxy: false
          # Override Masakari services on non-controllers (overrides default
          # plugin settings in Masakari). Only monitors are left.
          masakari-api: false
          masakari-engine: false
          # NOTE(yoctozepto): Disable compute's cinder (c-* services).
          # It is enabled by default by the parent job (devstack) definition.
          cinder: false

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
      - periodic-jobs-with-oslo-master
    check:
      jobs:
        - openstack-tox-linters
        - masakari-functional-devstack-multinode:
            voting: true
    gate:
      jobs:
        - openstack-tox-linters
    periodic:
      jobs:
        - masakari-functional-devstack-multinode
